# Site settings
title: "TrentonZero's Thoughts"
tagline: "You Wanted More, you got it."
production_url: https://trentonzero.github.io
permalink: /:year/:month/:title

exclude: [".hyde.el", ".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "Dockerfile", "docker-compose.yml"]
highlighter: rouge
excerpt_separator: "<!-- more -->"

# Author
author:
  name: Kevin Walker
  email: trentonzero@gmail.com
  github: trentonzero
  twitter: trentonzero

# Comments (Disqus)
disqus_shortname: trentonzero

# Analytics (Google)
google_analytics: "UA-56738481-1"
